export const patientFieldGroups = [
  {
    title: "Basic Information",
    fields: [
      ["patient_id", "Patient ID", "text", true, true],
      ["date_registered", "Date Registered", "date", true, true],
      ["branch_location", "Branch Location", "datalist", false, false, ["Lilac", "Marikina Public Market"]],
      ["last_name", "Last Name", "text", true],
      ["first_name", "First Name", "text", true],
      ["middle_name", "Middle Name", "text"],
      ["birthday", "Birthday", "date", true],
      ["age", "Age", "number", false, true],
      ["gender", "Gender", "select", true, false, ["", "Male", "Female", "Other"]],
      ["religion", "Religion", "select", false, false, ["", "Roman Catholic", "Christian", "Iglesia ni Cristo", "Islam", "Buddhism", "Hinduism", "Seventh-day Adventist", "Born Again Christian", "Jehovah's Witness", "Others", "Prefer not to say"]],
      ["nationality", "Nationality", "select", false, false, ["", "Filipino", "American", "Chinese", "Japanese", "Korean", "Indian", "British", "Canadian", "Australian", "Others"]],
      ["nickname", "Nickname", "text"],
      ["patient_occupation", "Patient Occupation", "text"],
      ["dental_insurance", "Dental Insurance", "text"],
      ["insurance_effective_date", "Insurance Effective Date", "date"],
      ["previous_dentist", "Previous Dentist", "text"],
      ["last_dental_visit", "Last Dental Visit", "date"],
      ["mobile_number", "Cellphone/Mobile Number", "text", true],
      ["email_address", "Email Address", "email"],
      ["discount_eligibility", "Patient Classification", "datalist", false, false, ["None", "Senior Citizen", "PWD", "Senior Citizen and PWD", "Other"]],
      ["home_address", "Home Address", "textarea"],
      ["home_number", "Home Number", "text"],
      ["office_number", "Office Number", "text"],
      ["fax_number", "Fax Number", "text"],
      ["is_minor", "Is Minor?", "select", false, false, ["No", "Yes"]],
      ["parent_guardian_name", "Parent/Guardian Name", "text"],
      ["parent_guardian_occupation", "Parent/Guardian Occupation", "text"],
      ["referral_source", "Referral Source / Person who referred the patient", "text"],
      ["reason_for_consultation", "Reason for Dental Consultation", "textarea"]
    ]
  },
  {
    title: "Medical History",
    fields: [
      ["good_health", "Are you in good health?", "select", false, false, ["", "Yes", "No"]],
      ["under_medical_treatment", "Are you under medical treatment now?", "select", false, false, ["", "Yes", "No"]],
      ["medical_treatment_details", "Medical Treatment Details", "textarea"],
      ["serious_illness_history", "Have you ever had serious illness or surgical operation?", "select", false, false, ["", "Yes", "No"]],
      ["serious_illness_details", "Serious Illness / Operation Details", "textarea"],
      ["hospitalized_history", "Have you ever been hospitalized?", "select", false, false, ["", "Yes", "No"]],
      ["hospitalization_details", "Hospitalization Details", "textarea"],
      ["taking_medications", "Are you taking prescription or non-prescription medication?", "select", false, false, ["", "Yes", "No"]],
      ["medication_details", "Medication Details", "textarea"],
      ["uses_tobacco", "Do you use tobacco products?", "select", false, false, ["", "Yes", "No"]],
      ["uses_alcohol_or_drugs", "Do you use alcohol, cocaine, or other dangerous drugs?", "select", false, false, ["", "Yes", "No"]],
      ["disability_type", "Type of Disability", "datalist", false, false, ["Physical Disability", "Visual Disability", "Hearing Disability", "Speech and Language Disability", "Psychosocial Disability", "Intellectual Disability", "Learning Disability", "Mental Disability", "Cancer", "Rare Disease", "Others"], "Shown only for PWD-related classification."],
      ["pregnant", "Are you pregnant?", "select", false, false, ["", "Yes", "No", "Not Applicable"]],
      ["nursing", "Are you nursing?", "select", false, false, ["", "Yes", "No", "Not Applicable"]],
      ["birth_control_pills", "Are you taking birth control pills?", "select", false, false, ["", "Yes", "No", "Not Applicable"]],
      ["physician_name", "Physician Name", "text"],
      ["physician_specialty", "Physician Specialty", "text"],
      ["physician_office_number", "Physician Office Number", "text"],
      ["physician_office_address", "Physician Office Address", "textarea"]
    ]
  },
  {
    title: "Allergy and Medical Risk",
    fields: [
      ["allergic_to_items", "Are you allergic to any listed items?", "select", false, false, ["", "Yes", "No"]],
      ["blood_type", "Blood Type", "select", false, false, ["", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Unknown"]],
      ["blood_pressure", "Blood Pressure", "text"],
      ["allergy_local_anesthetic", "Allergy - Local Anesthetic", "select", false, false, ["", "Yes", "No"]],
      ["local_anesthetic_details", "Local Anesthetic Details", "text"],
      ["allergy_penicillin", "Allergy - Penicillin / Antibiotics", "select", false, false, ["", "Yes", "No"]],
      ["allergy_sulfa", "Allergy - Sulfa Drugs", "select", false, false, ["", "Yes", "No"]],
      ["allergy_aspirin", "Allergy - Aspirin", "select", false, false, ["", "Yes", "No"]],
      ["allergy_latex", "Allergy - Latex", "select", false, false, ["", "Yes", "No"]],
      ["allergy_others", "Allergy - Others", "select", false, false, ["", "Yes", "No"]],
      ["allergy_others_details", "Allergy Others Details", "textarea"],
      ["other_medical_condition", "Other Medical Condition", "select", false, false, ["", "Yes", "No"]],
      ["other_medical_condition_details", "Other Medical Condition Details", "textarea"],
      ["medical_alert_summary", "Medical Alert Summary", "textarea", false, true]
    ]
  }
];

export const medicalConditionFields = [
  ["condition_high_blood_pressure", "High Blood Pressure"],
  ["condition_low_blood_pressure", "Low Blood Pressure"],
  ["condition_epilepsy_convulsions", "Epilepsy / Convulsions"],
  ["condition_aids_hiv", "AIDS or HIV Infection"],
  ["condition_std", "Sexually Transmitted Disease"],
  ["condition_stomach_troubles", "Stomach Troubles / Ulcers"],
  ["condition_fainting_seizure", "Fainting Seizure"],
  ["condition_rapid_weight_loss", "Rapid Weight Loss"],
  ["condition_radiation_therapy", "Radiation Therapy"],
  ["condition_joint_replacement", "Joint Replacement / Implant"],
  ["condition_heart_surgery", "Heart Surgery"],
  ["condition_heart_attack", "Heart Attack"],
  ["condition_thyroid_problem", "Thyroid Problem"],
  ["condition_heart_disease", "Heart Disease"],
  ["condition_heart_murmur", "Heart Murmur"],
  ["condition_hepatitis_liver_disease", "Hepatitis / Liver Disease"],
  ["condition_rheumatic_fever", "Rheumatic Fever"],
  ["condition_hay_fever_allergies", "Hay Fever / Allergies"],
  ["condition_respiratory_problems", "Respiratory Problems"],
  ["condition_hepatitis_jaundice", "Hepatitis / Jaundice"],
  ["condition_tuberculosis", "Tuberculosis"],
  ["condition_swollen_ankles", "Swollen Ankles"],
  ["condition_kidney_disease", "Kidney Disease"],
  ["condition_diabetes", "Diabetes"],
  ["condition_chest_pain", "Chest Pain"],
  ["condition_stroke", "Stroke"],
  ["condition_cancer_tumors", "Cancer / Tumors"],
  ["condition_anemia", "Anemia"],
  ["condition_angina", "Angina"],
  ["condition_asthma", "Asthma"],
  ["condition_emphysema", "Emphysema"],
  ["condition_bleeding_problems", "Bleeding Problems"],
  ["condition_blood_diseases", "Blood Diseases"],
  ["condition_head_injuries", "Head Injuries"],
  ["condition_arthritis_rheumatism", "Arthritis / Rheumatism"]
];

export const emptyPatient = {
  patient_id: "",
  date_registered: "",
  last_name: "",
  first_name: "",
  middle_name: "",
  birthday: "",
  age: "",
  gender: "",
  religion: "",
  nationality: "",
  nickname: "",
  patient_occupation: "",
  dental_insurance: "",
  insurance_effective_date: "",
  previous_dentist: "",
  last_dental_visit: "",
  mobile_number: "",
  email_address: "",
  branch_location: "",
  home_address: "",
  home_number: "",
  office_number: "",
  fax_number: "",
  is_minor: "No",
  parent_guardian_name: "",
  parent_guardian_occupation: "",
  referral_source: "",
  reason_for_consultation: "",
  good_health: "",
  under_medical_treatment: "",
  medical_treatment_details: "",
  serious_illness_history: "",
  serious_illness_details: "",
  hospitalized_history: "",
  hospitalization_details: "",
  taking_medications: "",
  medication_details: "",
  uses_tobacco: "",
  uses_alcohol_or_drugs: "",
  discount_eligibility: "None",
  disability_type: "",
  pregnant: "",
  nursing: "",
  birth_control_pills: "",
  physician_name: "",
  physician_specialty: "",
  physician_office_number: "",
  physician_office_address: "",
  allergic_to_items: "",
  blood_type: "",
  blood_pressure: "",
  allergy_local_anesthetic: "",
  local_anesthetic_details: "",
  allergy_penicillin: "",
  allergy_sulfa: "",
  allergy_aspirin: "",
  allergy_latex: "",
  allergy_others: "",
  allergy_others_details: "",
  other_medical_condition: "",
  other_medical_condition_details: "",
  medical_alert_summary: "",
  condition_high_blood_pressure: 0,
  condition_low_blood_pressure: 0,
  condition_epilepsy_convulsions: 0,
  condition_aids_hiv: 0,
  condition_std: 0,
  condition_stomach_troubles: 0,
  condition_fainting_seizure: 0,
  condition_rapid_weight_loss: 0,
  condition_radiation_therapy: 0,
  condition_joint_replacement: 0,
  condition_heart_surgery: 0,
  condition_heart_attack: 0,
  condition_thyroid_problem: 0,
  condition_heart_disease: 0,
  condition_heart_murmur: 0,
  condition_hepatitis_liver_disease: 0,
  condition_rheumatic_fever: 0,
  condition_hay_fever_allergies: 0,
  condition_respiratory_problems: 0,
  condition_hepatitis_jaundice: 0,
  condition_tuberculosis: 0,
  condition_swollen_ankles: 0,
  condition_kidney_disease: 0,
  condition_diabetes: 0,
  condition_chest_pain: 0,
  condition_stroke: 0,
  condition_cancer_tumors: 0,
  condition_anemia: 0,
  condition_angina: 0,
  condition_asthma: 0,
  condition_emphysema: 0,
  condition_bleeding_problems: 0,
  condition_blood_diseases: 0,
  condition_head_injuries: 0,
  condition_arthritis_rheumatism: 0
};

export const emptyTreatment = {
  treatment_id: "",
  patient_id: "",
  treatment_date: "",
  tooth_numbers: "",
  next_appointment: "",
  next_appointment_date: "",
  next_appointment_time: "",
  procedure: "",
  dentists: "",
  discount_type: "None",
  discount_percent: "0.00",
  discount_amount: "0.00",
  net_amount_due: "0.00",
  amount_charged: "",
  amount_paid: "",
  balance: "",
  remarks: ""
};

export const appointmentStatusOptions = ["Scheduled", "Completed", "Cancelled", "No-show"];

export const emptyAppointment = {
  appointment_date: "",
  appointment_time: "",
  planned_procedure: "",
  notes: "",
  status: "Scheduled"
};

export const suggestedDentists = ["Dr. Arlen C. Khurana"];

export const treatmentDiscountTypes = ["None", "Senior Citizen", "PWD", "Senior Citizen/PWD", "Custom"];

export const suggestedTreatmentProcedures = [
  "Oral Prophylaxis / Cleaning",
  "Tooth Extraction",
  "Dental Restoration / Pasta",
  "Tooth Filling",
  "Root Canal Treatment",
  "Denture Adjustment",
  "Denture Installation",
  "Crown Installation",
  "Bridge Installation",
  "Teeth Whitening",
  "Fluoride Treatment",
  "Dental Consultation",
  "Orthodontic Adjustment",
  "Braces Installation",
  "X-ray",
  "Surgery",
  "Follow-up Checkup",
  "Emergency Treatment"
];
