import type { BranchLocationMapping, LegacyPatientRow } from "./patientMigration.js";
import type { BranchRecord } from "./branches.js";

export const fictionalBranch: BranchRecord = {
  id: "11111111-1111-4111-8111-111111111111",
  branchCode: "FIC-ALPHA",
  branchName: "Fictional Alpha Clinic",
  createdAt: "2026-08-17T00:00:00.000Z",
  updatedAt: "2026-08-17T00:00:00.000Z"
};

export const fictionalBranchMappings: readonly BranchLocationMapping[] = [
  {
    legacyBranchLocation: "Fictional Alpha Front Desk",
    branchId: fictionalBranch.id
  }
];

export function buildFictionalLegacyPatientRow(overrides: Partial<LegacyPatientRow> = {}): LegacyPatientRow {
  return {
    id: 101,
    patient_id: "P-2026-0007",
    date_registered: "2026-08-01",
    last_name: "Example",
    first_name: "Pat",
    middle_name: "Morgan",
    birthday: "1992-03-14",
    age: 34,
    gender: "Female",
    religion: "Fictional Faith",
    nationality: "Fictional",
    nickname: "PM",
    patient_occupation: "Archivist",
    dental_insurance: "FictionalCare",
    insurance_effective_date: "2026-01-01",
    previous_dentist: "Dr. Fiction",
    last_dental_visit: "2026-07-15",
    mobile_number: "09171234567",
    email_address: "pat@example.test",
    branch_location: "Fictional Alpha Front Desk",
    discount_eligibility: "PWD",
    home_address: "123 Fictional Avenue",
    home_number: "02-8000-0000",
    office_number: "02-8111-1111",
    fax_number: "02-8222-2222",
    is_minor: "No",
    parent_guardian_name: null,
    parent_guardian_occupation: null,
    referral_source: "Friend",
    reason_for_consultation: "Routine cleaning",
    good_health: "Yes",
    under_medical_treatment: "No",
    medical_treatment_details: "",
    serious_illness_history: "No",
    serious_illness_details: "",
    hospitalized_history: "No",
    hospitalization_details: "",
    taking_medications: "No",
    medication_details: "",
    uses_tobacco: "No",
    uses_alcohol_or_drugs: "No",
    disability_type: "Mobility",
    pregnant: "No",
    nursing: "No",
    birth_control_pills: "No",
    physician_name: "Dr. Story",
    physician_specialty: "Family Medicine",
    physician_office_number: "02-8333-3333",
    physician_office_address: "456 Narrative Street",
    allergic_to_items: "Dust",
    blood_type: "O+",
    blood_pressure: "120/80",
    allergy_local_anesthetic: "No",
    local_anesthetic_details: "",
    allergy_penicillin: "Yes",
    allergy_sulfa: "No",
    allergy_aspirin: "No",
    allergy_latex: "No",
    allergy_others: "Yes",
    allergy_others_details: "Shellfish",
    condition_high_blood_pressure: 0,
    condition_low_blood_pressure: 0,
    condition_epilepsy_convulsions: 0,
    condition_aids_hiv: 0,
    condition_std: 0,
    condition_stomach_troubles: 0,
    condition_fainting_seizure: 0,
    condition_rapid_weight_loss: 0,
    condition_radiation_therapy: 0,
    condition_joint_replacement: 0,
    condition_heart_surgery: 0,
    condition_heart_attack: 0,
    condition_thyroid_problem: 0,
    condition_heart_disease: 0,
    condition_heart_murmur: 0,
    condition_hepatitis_liver_disease: 0,
    condition_rheumatic_fever: 0,
    condition_hay_fever_allergies: 1,
    condition_respiratory_problems: 0,
    condition_hepatitis_jaundice: 0,
    condition_tuberculosis: 0,
    condition_swollen_ankles: 0,
    condition_kidney_disease: 0,
    condition_diabetes: 0,
    condition_chest_pain: 0,
    condition_stroke: 0,
    condition_cancer_tumors: 0,
    condition_anemia: 0,
    condition_angina: 0,
    condition_asthma: 1,
    condition_emphysema: 0,
    condition_bleeding_problems: 0,
    condition_blood_diseases: 0,
    condition_head_injuries: 0,
    condition_arthritis_rheumatism: 0,
    other_medical_condition: "No",
    other_medical_condition_details: "",
    medical_alert_summary: "Allergies: Penicillin / Antibiotics, Other Allergies (Shellfish) | Patient classification: PWD | Type of disability: Mobility",
    created_at: "2026-08-01T08:00:00.000Z",
    updated_at: "2026-08-05T10:30:00.000Z",
    ...overrides
  };
}
