CREATE TABLE IF NOT EXISTS branches (
  id UUID PRIMARY KEY,
  branch_code TEXT NOT NULL UNIQUE,
  branch_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT branches_branch_code_not_blank CHECK (length(trim(branch_code)) > 0),
  CONSTRAINT branches_branch_name_not_blank CHECK (length(trim(branch_name)) > 0)
);

CREATE TABLE IF NOT EXISTS patient_code_counters (
  calendar_year INTEGER PRIMARY KEY,
  last_sequence INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT patient_code_counters_year_positive CHECK (calendar_year >= 2000),
  CONSTRAINT patient_code_counters_sequence_positive CHECK (last_sequence >= 1)
);

CREATE TABLE IF NOT EXISTS patients (
  id UUID PRIMARY KEY,
  patient_code TEXT NOT NULL UNIQUE,
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  date_registered DATE NOT NULL,
  last_name TEXT NOT NULL,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  birthday DATE NOT NULL,
  age INTEGER,
  gender TEXT NOT NULL,
  religion TEXT,
  nationality TEXT,
  nickname TEXT,
  patient_occupation TEXT,
  dental_insurance TEXT,
  insurance_effective_date DATE,
  previous_dentist TEXT,
  last_dental_visit DATE,
  mobile_number TEXT NOT NULL,
  email_address TEXT,
  discount_eligibility TEXT NOT NULL DEFAULT 'None',
  home_address TEXT,
  home_number TEXT,
  office_number TEXT,
  fax_number TEXT,
  is_minor TEXT,
  parent_guardian_name TEXT,
  parent_guardian_occupation TEXT,
  referral_source TEXT,
  reason_for_consultation TEXT,
  good_health TEXT,
  under_medical_treatment TEXT,
  medical_treatment_details TEXT,
  serious_illness_history TEXT,
  serious_illness_details TEXT,
  hospitalized_history TEXT,
  hospitalization_details TEXT,
  taking_medications TEXT,
  medication_details TEXT,
  uses_tobacco TEXT,
  uses_alcohol_or_drugs TEXT,
  disability_type TEXT,
  pregnant TEXT,
  nursing TEXT,
  birth_control_pills TEXT,
  physician_name TEXT,
  physician_specialty TEXT,
  physician_office_number TEXT,
  physician_office_address TEXT,
  allergic_to_items TEXT,
  blood_type TEXT,
  blood_pressure TEXT,
  allergy_local_anesthetic TEXT,
  local_anesthetic_details TEXT,
  allergy_penicillin TEXT,
  allergy_sulfa TEXT,
  allergy_aspirin TEXT,
  allergy_latex TEXT,
  allergy_others TEXT,
  allergy_others_details TEXT,
  condition_high_blood_pressure BOOLEAN NOT NULL DEFAULT FALSE,
  condition_low_blood_pressure BOOLEAN NOT NULL DEFAULT FALSE,
  condition_epilepsy_convulsions BOOLEAN NOT NULL DEFAULT FALSE,
  condition_aids_hiv BOOLEAN NOT NULL DEFAULT FALSE,
  condition_std BOOLEAN NOT NULL DEFAULT FALSE,
  condition_stomach_troubles BOOLEAN NOT NULL DEFAULT FALSE,
  condition_fainting_seizure BOOLEAN NOT NULL DEFAULT FALSE,
  condition_rapid_weight_loss BOOLEAN NOT NULL DEFAULT FALSE,
  condition_radiation_therapy BOOLEAN NOT NULL DEFAULT FALSE,
  condition_joint_replacement BOOLEAN NOT NULL DEFAULT FALSE,
  condition_heart_surgery BOOLEAN NOT NULL DEFAULT FALSE,
  condition_heart_attack BOOLEAN NOT NULL DEFAULT FALSE,
  condition_thyroid_problem BOOLEAN NOT NULL DEFAULT FALSE,
  condition_heart_disease BOOLEAN NOT NULL DEFAULT FALSE,
  condition_heart_murmur BOOLEAN NOT NULL DEFAULT FALSE,
  condition_hepatitis_liver_disease BOOLEAN NOT NULL DEFAULT FALSE,
  condition_rheumatic_fever BOOLEAN NOT NULL DEFAULT FALSE,
  condition_hay_fever_allergies BOOLEAN NOT NULL DEFAULT FALSE,
  condition_respiratory_problems BOOLEAN NOT NULL DEFAULT FALSE,
  condition_hepatitis_jaundice BOOLEAN NOT NULL DEFAULT FALSE,
  condition_tuberculosis BOOLEAN NOT NULL DEFAULT FALSE,
  condition_swollen_ankles BOOLEAN NOT NULL DEFAULT FALSE,
  condition_kidney_disease BOOLEAN NOT NULL DEFAULT FALSE,
  condition_diabetes BOOLEAN NOT NULL DEFAULT FALSE,
  condition_chest_pain BOOLEAN NOT NULL DEFAULT FALSE,
  condition_stroke BOOLEAN NOT NULL DEFAULT FALSE,
  condition_cancer_tumors BOOLEAN NOT NULL DEFAULT FALSE,
  condition_anemia BOOLEAN NOT NULL DEFAULT FALSE,
  condition_angina BOOLEAN NOT NULL DEFAULT FALSE,
  condition_asthma BOOLEAN NOT NULL DEFAULT FALSE,
  condition_emphysema BOOLEAN NOT NULL DEFAULT FALSE,
  condition_bleeding_problems BOOLEAN NOT NULL DEFAULT FALSE,
  condition_blood_diseases BOOLEAN NOT NULL DEFAULT FALSE,
  condition_head_injuries BOOLEAN NOT NULL DEFAULT FALSE,
  condition_arthritis_rheumatism BOOLEAN NOT NULL DEFAULT FALSE,
  other_medical_condition TEXT,
  other_medical_condition_details TEXT,
  medical_alert_summary TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT patients_patient_code_not_blank CHECK (length(trim(patient_code)) > 0),
  CONSTRAINT patients_first_name_not_blank CHECK (length(trim(first_name)) > 0),
  CONSTRAINT patients_last_name_not_blank CHECK (length(trim(last_name)) > 0),
  CONSTRAINT patients_gender_not_blank CHECK (length(trim(gender)) > 0),
  CONSTRAINT patients_mobile_number_not_blank CHECK (length(trim(mobile_number)) > 0),
  CONSTRAINT patients_discount_eligibility_not_blank CHECK (length(trim(discount_eligibility)) > 0)
);

CREATE TABLE IF NOT EXISTS legacy_patient_identity_map (
  source_system TEXT NOT NULL,
  legacy_patient_row_id BIGINT NOT NULL,
  legacy_patient_code TEXT NOT NULL,
  patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT legacy_patient_identity_map_source_not_blank CHECK (length(trim(source_system)) > 0),
  CONSTRAINT legacy_patient_identity_map_code_not_blank CHECK (length(trim(legacy_patient_code)) > 0),
  CONSTRAINT legacy_patient_identity_map_source_row_unique UNIQUE (source_system, legacy_patient_row_id),
  CONSTRAINT legacy_patient_identity_map_source_code_unique UNIQUE (source_system, legacy_patient_code),
  CONSTRAINT legacy_patient_identity_map_patient_unique UNIQUE (patient_id)
);
